# Generated by Django 5.0.6 on 2026-07-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={"ordering": ["first_name"]},
        ),
        migrations.AddField(
            model_name="teacher",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacher",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacher",
            name="last_device",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="teacher",
            name="last_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="remember_device",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacher",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="role",
            field=models.CharField(
                choices=[("teacher", "Teacher"), ("principal", "Principal / HOD")],
                default="teacher",
                max_length=20,
            ),
        ),
    ]
