# Generated by Django 5.0.6 on 2026-07-04 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_passwordotp"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("device_name", models.CharField(max_length=255)),
                ("browser", models.CharField(max_length=100)),
                ("operating_system", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("remember_until", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_login"],
            },
        ),
    ]
