# Generated by Django 5.0.6 on 2026-07-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordotp",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
