# Generated by Django 5.0.6 on 2026-09-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple choice questions"),
                    ("ftq", "Following the questions"),
                    ("cs", "Case Study"),
                ],
                max_length=20,
            ),
        ),
    ]
