# Generated by Django 5.0.6 on 2026-09-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_alter_question_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="bloom_level",
            field=models.CharField(
                choices=[
                    ("1", "Remember"),
                    ("2", "Understand"),
                    ("3", "Apply"),
                    ("4", "Analyze"),
                    ("5", "Evaluate"),
                    ("6", "Create"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple choice questions"),
                    ("ftq", "Following the questions"),
                    ("cs", "Case Study"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="unit",
            field=models.CharField(
                choices=[
                    ("1", "Unit 1"),
                    ("2", "Unit 2"),
                    ("3", "Unit 3"),
                    ("4", "Unit 4"),
                    ("5", "Unit 5"),
                    ("6", "Unit 6"),
                    ("7", "Unit 7"),
                    ("8", "Unit 8"),
                    ("All", "All Units"),
                ],
                max_length=3,
            ),
        ),
    ]
