# Generated by Django 5.0.6 on 2026-09-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_alter_question_bloom_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
