# Generated by Django 5.0.6 on 2026-06-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="level",
            field=models.CharField(
                choices=[("UG", "Under Graduate"), ("PG", "Post Graduate")],
                default="ug",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
