# Generated by Django 5.0.6 on 2026-06-19 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_program_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semester",
            name="name",
        ),
        migrations.AddField(
            model_name="semester",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="program",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.program",
            ),
        ),
    ]
