# Generated by Django 5.0.6 on 2026-07-03 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("total_marks", models.PositiveIntegerField()),
                ("section_a_count", models.PositiveIntegerField(default=0)),
                ("section_a_marks", models.PositiveIntegerField(default=0)),
                ("section_b_count", models.PositiveIntegerField(default=0)),
                ("section_b_marks", models.PositiveIntegerField(default=0)),
                ("section_c_count", models.PositiveIntegerField(default=0)),
                ("section_c_marks", models.PositiveIntegerField(default=0)),
                ("easy_percentage", models.PositiveIntegerField(default=30)),
                ("medium_percentage", models.PositiveIntegerField(default=40)),
                ("hard_percentage", models.PositiveIntegerField(default=20)),
                ("long_answer_percentage", models.PositiveIntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patterns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "college_name",
                    models.CharField(default="ABC COLLEGE", max_length=200),
                ),
                ("subject", models.CharField(max_length=100)),
                ("time_allowed", models.CharField(default="3 Hours", max_length=50)),
                ("maximum_marks", models.PositiveIntegerField()),
                ("exam_date", models.DateField(auto_now_add=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="generated_papers/pdf/"
                    ),
                ),
                (
                    "docx_file",
                    models.FileField(
                        blank=True, null=True, upload_to="generated_papers/docx/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section_a_questions",
                    models.ManyToManyField(
                        related_name="section_a_papers", to="questions.question"
                    ),
                ),
                (
                    "section_b_questions",
                    models.ManyToManyField(
                        related_name="section_b_papers", to="questions.question"
                    ),
                ),
                (
                    "section_c_questions",
                    models.ManyToManyField(
                        related_name="section_c_papers", to="questions.question"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_papers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="papers.paperpattern",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
