# Generated by Django 5.0.6 on 2026-07-13 19:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_remove_semester_name_semester_number_subject_program"),
        ("papers", "0001_initial"),
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatedpaper",
            name="college_name",
        ),
        migrations.RemoveField(
            model_name="generatedpaper",
            name="exam_date",
        ),
        migrations.RemoveField(
            model_name="generatedpaper",
            name="maximum_marks",
        ),
        migrations.RemoveField(
            model_name="generatedpaper",
            name="section_a_questions",
        ),
        migrations.RemoveField(
            model_name="generatedpaper",
            name="section_b_questions",
        ),
        migrations.RemoveField(
            model_name="generatedpaper",
            name="section_c_questions",
        ),
        migrations.RemoveField(
            model_name="generatedpaper",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="generatedpaper",
            name="time_allowed",
        ),
        migrations.RemoveField(
            model_name="paperpattern",
            name="easy_percentage",
        ),
        migrations.RemoveField(
            model_name="paperpattern",
            name="hard_percentage",
        ),
        migrations.RemoveField(
            model_name="paperpattern",
            name="long_answer_percentage",
        ),
        migrations.RemoveField(
            model_name="paperpattern",
            name="medium_percentage",
        ),
        migrations.RemoveField(
            model_name="paperpattern",
            name="name",
        ),
        migrations.RemoveField(
            model_name="paperpattern",
            name="section_a_count",
        ),
        migrations.RemoveField(
            model_name="paperpattern",
            name="section_a_marks",
        ),
        migrations.RemoveField(
            model_name="paperpattern",
            name="section_b_count",
        ),
        migrations.RemoveField(
            model_name="paperpattern",
            name="section_b_marks",
        ),
        migrations.RemoveField(
            model_name="paperpattern",
            name="section_c_count",
        ),
        migrations.RemoveField(
            model_name="paperpattern",
            name="section_c_marks",
        ),
        migrations.AddField(
            model_name="paperpattern",
            name="exam_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paperpattern",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular End Semester"),
                    ("midterm", "Mid Semester"),
                    ("internal", "Internal Assessment"),
                    ("practical", "Practical"),
                    ("custom", "Custom"),
                ],
                default="regular",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paperpattern",
            name="instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paperpattern",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paperpattern",
            name="paper_header",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paperpattern",
            name="pattern_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paperpattern",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.program",
            ),
        ),
        migrations.AddField(
            model_name="paperpattern",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.semester",
            ),
        ),
        migrations.AddField(
            model_name="paperpattern",
            name="time_allowed",
            field=models.CharField(default="1 Hour", max_length=50),
        ),
        migrations.AlterField(
            model_name="paperpattern",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.subject",
            ),
        ),
        migrations.AlterField(
            model_name="paperpattern",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_patterns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PatternSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.PositiveIntegerField()),
                ("question_number", models.CharField(max_length=20)),
                (
                    "attempt_rule",
                    models.CharField(
                        choices=[
                            ("all", "Attempt All"),
                            ("1of2", "Attempt Any 1 out of 2"),
                            ("2of3", "Attempt Any 2 out of 3"),
                            ("custom", "Custom"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("custom_attempt_text", models.CharField(blank=True, max_length=200)),
                ("unit", models.CharField(max_length=10)),
                ("bloom_level", models.CharField(max_length=30)),
                ("difficulty", models.CharField(max_length=20)),
                ("question_type", models.CharField(max_length=30)),
                ("marks", models.PositiveIntegerField()),
                ("number_of_questions", models.PositiveIntegerField(default=1)),
                (
                    "pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="papers.paperpattern",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.PositiveIntegerField()),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_questions",
                        to="papers.generatedpaper",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="papers.patternsection",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
    ]
