# Generated by Django 5.0.6 on 2026-07-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0002_remove_generatedpaper_college_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patternsection",
            name="co",
            field=models.CharField(default="CO1", max_length=10),
        ),
    ]
