# Generated by Django 5.0.6 on 2026-09-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0003_patternsection_co"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patternsection",
            name="attempt_rule",
            field=models.CharField(
                choices=[
                    ("all", "Attempt All"),
                    ("1of2", "Attempt Any 1 out of 2"),
                    ("2of3", "Attempt Any 2 out of 3"),
                    ("3of4", "Attempt Any 3 out of 4"),
                    ("4of5", "Attempt Any 4 out of 5"),
                    ("custom", "Custom"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="patternsection",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple choice questions"),
                    ("ftq", "Following the questions"),
                    ("cs", "Case Study"),
                ],
                default="mcq",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="patternsection",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
