# Generated by Django 5.0.6 on 2026-09-09 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0004_alter_patternsection_attempt_rule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatternQuestionSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_number", models.PositiveIntegerField()),
                ("bloom_level", models.CharField(default="1", max_length=30)),
                ("co", models.CharField(default="CO1", max_length=10)),
                ("difficulty", models.CharField(default="Easy", max_length=20)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_settings",
                        to="papers.patternsection",
                    ),
                ),
            ],
            options={
                "ordering": ["slot_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="patternquestionsetting",
            constraint=models.UniqueConstraint(
                fields=("section", "slot_number"), name="unique_section_slot"
            ),
        ),
    ]
