# Generated by Django 5.0.6 on 2026-09-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0005_patternquestionsetting_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patternsection",
            name="attempt_rule",
            field=models.CharField(
                choices=[
                    ("select attempt rule ", "Select Attempt Rule"),
                    ("1of2", "Attempt Any 1 out of 2"),
                    ("2of3", "Attempt Any 2 out of 3"),
                    ("3of4", "Attempt Any 3 out of 4"),
                    ("4of5", "Attempt Any 4 out of 5"),
                    ("5of5", "Attempt every question"),
                    ("custom", "Custom"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
