# Generated by Django 5.0.6 on 2026-09-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0007_alter_patternsection_attempt_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="patternquestionsetting",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
