# Generated by Django 5.0.6 on 2026-09-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0008_patternquestionsetting_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedquestion",
            name="is_manual_replacement",
            field=models.BooleanField(default=False),
        ),
    ]
